"""empty message

Revision ID: 4849696727c0
Revises:
Create Date: 2026-01-19 16:33:33.797835

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4849696727c0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("task_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("task_id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("name", name=op.f("uq_tasks_name")),
    )
    op.create_table(
        "links",
        sa.Column("link_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("redirect_urls", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("referer", sa.Text(), nullable=False),
        sa.Column("task_id", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "(status >= 100 AND status < 600) OR status = 888 OR status = 999",
            name=op.f("ck_links_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.task_id"], name=op.f("fk_links_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("link_id", name=op.f("pk_links")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("links")
    op.drop_table("tasks")
    # ### end Alembic commands ###
